totaldebug/pyarr

- PyArr/radarr_api.py
Now `getMovie()` has 1:1 code parity with `getSeries()`.
If passing in no arguments, `getMovie()` would crash due to indexing to element 0 on a NoneType.
> Fix bug regarding passing in no args to getMovie()

- pyarr/sonarr_api.py
- pyproject.toml
When attempting to call the lookup_series function it would throw an error because it was using the old function call lookupSeries instead of lookup_series
Pull github repo and write a script to utilize the lookup_series function built into the SonarrAPI
Because at the moment the package doesn't work without changing the code
I am building a discord bot to utilize this library
> Made change to sonarrAPI. Changed lookupSeries to lookup_series

- pyarr/radarr_api_v3.py
- pyproject.toml
When adding a movie the default path for the movie was not appropriate in all scenario's, this change ensures that the root path is used and then Radarr will name the subfolders as required. 
- fixes #62 
Fixes an issue experienced by some users
tested in my lab
> fix: resolves issue with naming of add_movies foldernames

- pyarr/sonarr_api.py
- pyproject.toml
Rename sonarr's `set_command` to `post_command` be consistent with RadarrAPI.
> SonarrAPI set_command() -> post_command()

- pyarr/radarr_api.py
- pyproject.toml
On 2.0.0 I accidentally didn't use put in verbose function parameters on `del_movie`.
This changes the parameter `del_files` ->`delete_files` to match SonarrAPI's `del_series` function.
> RadarrAPI del_files -> delete_files

- pyarr/radarr_api.py
- pyarr/sonarr_api.py
- pyproject.toml
- Fixes bug where SonarrAPI could add series to wrong folder
- Cleans up RadarrAPI construct_movie_json to match sonarr's equivalent
- Adds RadarrAPI `lookup_movie_by_imdb_id()`
> Fix json constructor

- pyarr/sonarr_api.py
- pyproject.toml
- Use Sonarr's internal folder naming schema
---
Currently, we're manually creating folder names for Sonarr. This is a bad idea, since it doesn't work for anyone who has customized Sonarr's folder naming schema. Additionally, the way we've been doing it does not safely handling string encoding.
So I pushed a minor change, now we'll only tell Sonarr what the root folder path should be and have it decide the rest.
> Sonarr Auto Folder Naming

- pyarr/radarr_api.py
- pyproject.toml
The del_movie_file function was deleting the movie not the moviefile
fix bug
> fix: Delete moviefile not movie

- pyarr/radarr_api.py
- pyproject.toml
Looks like we somehow accidentally forgot to use the `/api/v3` endpoint for PUT /movie.
This PR fixes that.
> fix: PUT /movie on Radarr v4

- pyarr/radarr_api.py
- pyproject.toml
Looks like there was a typo that got merged in.
`path.request_put` -> `self.request_put`
> fix: incorrect Radarr request queries

- pyarr/radarr_api.py
- pyarr/sonarr_api.py
- pyproject.toml
This PR uses [Sourcery](https://sourcery.ai/) to automatically refactor our code to minimize memory usage and improve readablity.
> Refactor using Sourcery

- .pylintrc
- pyarr/base.py
- pyarr/exceptions.py
- pyarr/radarr.py
- pyarr/readarr.py
- pyarr/request_handler.py
- pyproject.toml
This fixes endpoints that were broken during the v3 release, and also addresses any pylint errors that were created.
- fix #94
> fix: broken endpoints and pylint errors

- pyarr/__init__.py
- pyarr/base.py
- pyarr/const.py
- pyarr/exceptions.py
- pyarr/lidarr.py
- pyarr/radarr.py
- pyarr/readarr.py
- pyarr/request_handler.py
- pyarr/sonarr.py
- pyproject.toml
- sphinx-docs/conf.py
Adding support for the Lidarr API
closes #81 
Adds additional support for new arr APIs
Most functions have been tested, however tests still need to be setup for this PR
> feat: Adding Lidarr API

- pyarr/sonarr.py
- pyproject.toml
Looks like you tried to use a `/v3` endpoint namespace within Sonarr when pushing out the Readarr updates...
However, the `/v3` endpoint within Sonarr is severely underdeveloped and is not suggested for production use.
This PR reverts back to the unversioned endpoint for compatibility purposes. The unversioned endpoint is the only one actively maintained by the Sonarr team.
> fix: Sonarr endpoint compatibility

- .github/workflows/greetings.yml
- pyarr/radarr.py
- pyarr/sonarr.py
- pyproject.toml
> Add Sonarr version URI

- pyarr/sonarr.py
Fixes #103.
Adds overrides just for Sonarr instead of moving everything to the subclasses of `BaseArrAPI`, since it seems to be the odd one out (I wonder why?). Technically by the naming pyarr has been following, it should conform to [Sonarr's wiki](https://github.com/Sonarr/Sonarr/wiki/Profile) and the functions should be `get_profile`, `upd_profile`, etc, but that just seems confusing for people using pyarr.
> Add overrides for Sonarr quality profile commands

- .github/workflows/pr.yml
- .github/workflows/release.yml
- mypy.ini
- poetry.lock
- pyarr/base.py
- pyarr/exceptions.py
- pyarr/lidarr.py
- pyarr/models/common.py
- pyarr/models/lidarr.py
- pyarr/models/radarr.py
- pyarr/models/readarr.py
- pyarr/models/sonarr.py
- pyarr/radarr.py
- pyarr/readarr.py
- pyarr/request_handler.py
- pyarr/sonarr.py
- pyproject.toml
This PR Adds Type hints. 
Some arguments have been updated to allow better support of type hints, this change will only allow correct values to be specified for these items listed below:
- `sort_dir` 
- `sort_keys` 
- `artist_monitor`
- `commands` 
Now accepts datetime instead of strings where a date is required. 
- #105 
By adding support for type hints the module is easier to use and ensure the correct data is provided / returned. 
Testing still on-going
> feat: added type hints

- .gitignore
- pyarr/sonarr.py
- pyproject.toml
- Fixed some incorrect type hints
- Added deprecation warning to functions in favour of new `get_episode()` function, this allows the same functionality in a single function.
` get_episode_by_episode_id`
`get_episode_by_series_id`
- Resolved assertion errors caused by adding type hints
- Fixes #108 
Resolves issues with the latest release
This has been tested in my lab
> fix: upd_episode throws error when supplying data

- pyarr/base.py
- pyarr/lidarr.py
- pyarr/radarr.py
- pyarr/readarr.py
- pyarr/request_handler.py
- pyarr/sonarr.py
- pyproject.toml
Fixes assertion errors for delete records when using Sonarr.
fixes #110 
resolves a bug added with type hints
Tested in lab
> fix: issue with assertion for sonarr deletes

- pyarr/sonarr.py
- pyproject.toml
Adds new arg `include_series` for the `get_wanted` method in Sonarr
fixes #114 
Adds missing functionality
Tested in lab
> feat: sonarr - inclide_serise added to get_wanted

- noxfile.py
- poetry.lock
- pyproject.toml
Add show locals and reruns to tests to enable easier debugging and rerunning of failed tasks as they sometimes fail due to the arr apis. 
fixes #130
> ci: add showlocals and reruns

- pyarr/radarr.py
- pyarr/readarr.py
- pyarr/sonarr.py
- tests/test_lidarr.py
- tests/test_radarr.py
- tests/test_readarr.py
- tests/test_sonarr.py
Adds the endpoint for `manualimport`
resolve #126
> feat: added manualimport endpoint

- pyarr/base.py
- pyarr/lidarr.py
- pyarr/models/common.py
- pyarr/models/lidarr.py
- pyarr/models/sonarr.py
- pyarr/radarr.py
- pyarr/readarr.py
- pyarr/request_handler.py
- pyarr/sonarr.py
- tests/test_lidarr.py
- tests/test_radarr.py
- tests/test_readarr.py
- tests/test_sonarr.py
> fix: multiple test failures since adding 500 exception

- pyarr/models/radarr.py
- pyproject.toml
- tests/test_radarr.py
add MoviesSearch to post_commands. undocumented API that is the radarr equivalent of sonarr EpisodeSearch. It triggers a search for the given movie the same as clicking the "Search Movie" button in the UI.
Closes #155 
Tested in a python script on my system against a live Radarr installation. I used info from this Radarr issue https://github.com/Radarr/Radarr/issues/3315
[Script used to test](https://github.com/LRomandine/servarr_upgrade_library/tree/main)
> Add undocumented MoviesSearch to post_commands

- pyarr/lib/alias_decorator.py
- pyarr/radarr.py
- pyarr/sonarr.py
- pyproject.toml
- tests/test_radarr.py
- tests/test_sonarr.py
This PR adds the ability to create function aliases, this has been added to allow standardisation of naming without breaking changes and allowing a deprecation warning. 
It also adds the release/push api to Radarr.
closes #158
> feat: added ability to create alias method names & added release/push to Radarr
